name: GHDL

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghdl/ghdl:5.0.0-dev-gcc-ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup and Run Build
        run: |
          apt update && apt install -y ant python3 python3-pip
          pip3 install --break-system-packages click jinja2

      - name: Generate Test Ant Skript
        run: ant _helper-generate-ghdl-ant-build-xml

      - name: Run Simulation
        run: ant ghdl-all

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ghdl-test-results
          path: simulation/SimulationResults/
